[package]
name = "rust_md_parser"
version = "0.1.0"
authors = ["Subbu <subala@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
